src/posts/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from .views import (
	PostCreateView,
	PostUpdateView,
	PostDetailView,
	PostListView,
	PostDeleteView)

urlpatterns = [
    url(r'^$', view=PostListView.as_view(), name="list"),
    url(r'^create/$', view=PostCreateView.as_view(), name="create"),
    url(r'^(?P<slug>[\w-]+)/$', view=PostDetailView.as_view(), name="detail"),
    url(r'^(?P<slug>[\w-]+)/edit/$', view=PostUpdateView.as_view(), name="update"),
    url(r'^(?P<slug>[\w-]+)/delete/$', view=PostDeleteView.as_view(), name="delete"),
]

src/trydjango19/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^accounts/', include('allauth.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^posts/', include('posts.urls', namespace='posts')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/posts/models.py
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.utils import timezone


class PostManager(models.Manager):

    def active(self, *args, **kwargs):
        return super(PostManager, self).filter(
            draft=False).filter(publish__lte=timezone.now())


def upload_location(instance, filename):
    return "{0}/{1}".format(instance.id, filename)


class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    title = models.CharField(max_length=120)
    slug = models.SlugField(unique=True, default='abv')
    image = models.ImageField(upload_to=upload_location,
                              null=True,
                              blank=True,
                              width_field="width_field",
                              height_field="height_field")
    width_field = models.IntegerField(default=0)
    height_field = models.IntegerField(default=0)
    content = models.TextField()
    draft = models.BooleanField(default=False)
    publish = models.DateField(auto_now_add=False, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)

    objects = PostManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("posts:detail", kwargs={"slug": self.slug})

    class Meta:
        ordering = ["-timestamp", "-updated"]


def pre_save_slug_post(sender, instance, *args, **kwargs):
    slug = slugify(instance.title)
    instance.slug = slug

pre_save.connect(pre_save_slug_post, sender=Post)

src/posts/forms.py
from django import forms
from django.utils.text import slugify

from .models import Post


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ("title", "content", "image", "draft", "publish")

    def clean_title(self):
        title = self.cleaned_data["title"]
        slug = slugify(title)
        try:
            Post.objects.get(slug=slug)
            error_msg = forms.ValidationError("This title already exist.")
            self.add_error('title', error_msg)
        except:
            return title

src/posts/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.urlresolvers import reverse_lazy
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Q
from django.http import Http404
from django.utils import timezone
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from braces.views import LoginRequiredMixin

from .forms import PostForm
from .models import Post


class PostCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    form_class = PostForm
    template_name = "posts/post_form.html"
    success_message = "Your post was created successfully."

    def get_context_data(self, *args, **kwargs):
        context = super(PostCreateView, self).get_context_data(*args, **kwargs)
        if self.request.user.is_staff:
            return context
        raise Http404

    def post(self, *args, **kwargs):

        form = self.get_form()
        if form.is_valid():
            form.user = self.request.user
            return self.form_valid(form)


class PostUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Post
    form_class = PostForm
    template_name = "posts/post_form.html"
    success_message = "Your post was updated successfully."

    def get_context_data(self, *args, **kwargs):
        context = super(PostCreateView, self).get_context_data(*args, **kwargs)
        if self.request.user.is_staff:
            return context
        raise Http404


class PostDetailView(DetailView):
    model = Post

    def get_context_data(self, *args, **kwargs):
        context = super(PostDetailView, self).get_context_data(*args, **kwargs)
        if context["object"].draft or context["object"].publish > timezone.now().date():
            if self.request.user.is_staff:
                return context
        raise Http404


class PostListView(ListView):
    model = Post

    def get_context_data(self, *args, **kwargs):
        context = super(PostListView, self).get_context_data(*args, **kwargs)
        q = self.request.GET.get("q")
        qs = (
                    Q(title__icontains=q) |
                    Q(content__icontains=q) |
                    Q(user__first_name__icontains=q) |
                    Q(user__last_name__icontains=q)
                )
        if self.request.user.is_staff:
            if q:
                object_list = Post.objects.filter(qs).distinct()
            else:
                object_list = Post.objects.all()
        else:
            if q:
                object_list = Post.objects.active().filter(qs)
            else:
                object_list = Post.objects.active()

        paginator = Paginator(object_list, 2)  # Show 5 results per page

        page = self.request.GET.get('page')
        try:
            object_list = paginator.page(page)
            page_range = paginator.page_range
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            object_list = paginator.page(1)
            page_range = paginator.page_range
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of
            # results.
            object_list = paginator.page(paginator.num_pages)
            page_range = paginator.page_range

        context["object_list"] = object_list
        context["page_range"] = page_range
        return context


class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy("posts:list")
    success_message = "Your post was deleted successfully."

    def get_context_data(self, *args, **kwargs):
        context = super(PostCreateView, self).get_context_data(*args, **kwargs)
        if self.request.user.is_staff:
            return context
        raise Http404

    def delete(self, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(PostDeleteView, self).delete(*args, **kwargs)

src/templates/base.html
<!DOCTYPE html>
<html lang="">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Title Page</title>

		<!-- Bootstrap CSS -->
		<link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">

	</head>
	<body>
		<!-- <h1 class="text-center">Welcome to the blog</h1> -->
		{% for message in messages %}
			<div class="alert alert-success text-center" role="alert">{{ message }}</div>
		{% endfor %}
		<div class="container">
		{% block content %}

		{% endblock content %}
		</div>
		<!-- jQuery -->
		<script src="//code.jquery.com/jquery.js"></script>
		<!-- Bootstrap JavaScript -->
		<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

		<!-- <div id="fb-root"></div> -->
		<script>(function(d, s, id) {
		  var js, fjs = d.getElementsByTagName(s)[0];
		  if (d.getElementById(id)) return;
		  js = d.createElement(s); js.id = id;
		  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.5";
		  fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));</script>
	</body>
</html>

src/templates/posts/pagination.html
<div class="col-sm-8 col-sm-offset-2">
	<ul class="pagination">
		{% if object_list.has_previous %}
			<li><a href="?page={{ object_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">&laquo;</a></li>
		{% endif %}
		{% if object_list.object_list %}
			{% for page_num in page_range %}
				<li {% if object_list.number == page_num %}class="active"{% endif %}><a href="?page={{ page_num }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ page_num }}</a></li>
			{% endfor %}
		{% endif %}
		{% if object_list.has_next %}
			<li><a href="?page={{ object_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">&raquo;</a></li>
		{% endif %}
	</ul>
</div>

src/templates/posts/post_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<form action="" method="POST" role="form">
	{% csrf_token %}
	<p>Are you sure you want to delete "{{ object }}"?</p>
	<button type="submit" class="btn btn-danger">Delete</button>

</form>
{% endblock content %}

src/templates/posts/post_detail.html
{% extends "base.html" %}

{% block content %}
	<div class="col-sm-8 col-sm-offset-2">
		<h2>{{ object.title }}</h2>
		{% if object.draft %} <h3>Draft</h3> {% endif %}
		<small>
			Author: 
			{% if object.user.get_full_name %}
				{{ object.user.get_full_name }}.
			{% else %} 
				{{ object.user.username }}.
			{% endif %}
			Published: {{ object.publish }}
		</small>
		<div class="thumbnail">
			{% if object.image %}
				<img src="{{ object.image.url }}" class="img-responsive" alt="">
			{% endif %}
			<div class="caption">
				
				<p>
					{{ object.content|linebreaks }}
				</p>
				<p>
					<a href="{% url 'posts:update' slug=object.slug %}" class="btn btn-primary">Update</a>
				</p>
			</div>
		</div>
		<p>
			<div class="fb-like" data-href="{{ request.build_absolute_uri }}" data-layout="button_count" data-action="like" data-show-faces="true" data-share="true"></div>
		</p>
		<div class="fb-comments" data-href="{{ request.build_absolute_uri }}" data-numposts="5"></div>
	</div>
	
{% endblock content %}

src/templates/posts/post_form.html
{% extends "base.html" %}

{% block content %}
<div class="col-sm-6 col-sm-offset-3">

	{% if object %}
		<h2>Update Post</h2>
		{% include "posts/template_form.html" with btn_name="Update" %}
	{% else %}
		<h2>New Post</h2>
		{% include "posts/template_form.html" %}
	{% endif %}
</div>
{% endblock content %}

src/templates/posts/post_list.html
{% extends "base.html" %}

{% block content %}
	<div class="col-sm-8 col-sm-offset-2">
		<h2 class="text-center">Posts</h2>
		<hr/>
		<form action="" method="GET" role="form">
			<input type="search" placeholder="Search" name="q" id="inputQ" class="form-control" value="{{ request.GET.q }}" title="">
			<button type="submit" class="btn btn-primary">Search</button>
		</form>
		
	</div>
	{% include "posts/pagination.html" with object_list=object_list page_range=page_range %}
	{% if object_list %}
		{% for post in object_list %}
			<div class="col-sm-8 col-sm-offset-2">
				<div class="thumbnail">
					{% if post.image %}
						<img src="{{ post.image.url }}" class="img-responsive" alt="">
					{% endif %}
					<div class="caption">
						<h3>{{ post.title }}</h3>
						{% if post.draft %} <h3>Draft</h3> {% endif %}
						<small>
						Author: 
							{% if post.user.get_full_name %}
								{{ post.user.get_full_name }}
							{% else %} 
								{{ post.user.username }}
							{% endif %}.
						Published: {{ post.publish }}
						</small>
						<p>
							{{ post.content|linebreaks|truncatechars:120 }}
						</p>
						<p>
							<a href="{{ post.get_absolute_url }}" class="btn btn-primary">View</a>
						</p>
					</div>
				</div>
			</div>
		{% endfor %}
	{% else %}
		<div class="col-sm-8 col-sm-offset-2">
			<h2 class="text-center">You have no posts</h2>
		</div>
	{% endif %}
	{% include "posts/pagination.html" with object_list=object_list page_range=page_range %}
	
{% endblock content %}

src/templates/posts/template_form.html
{% load crispy_forms_tags %}

<form action="" method="POST" role="form" enctype="multipart/form-data">
	{% csrf_token %}
	{{ form|crispy }}
	<button type="submit" class="btn btn-primary">{% if btn_name %}{{ btn_name }}{% else %}Create{% endif %}</button>
</form>